// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/observatory/multiobservatory/config.proto

package multiobservatory

import (
	serial "github.com/xtls/xray-core/common/serial"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Observers     []*ObserverConfig      `protobuf:"bytes,1,rep,name=observers,proto3" json:"observers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_observatory_multiobservatory_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetObservers() []*ObserverConfig {
	if x != nil {
		return x.Observers
	}
	return nil
}

type ObserverConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Settings      *serial.TypedMessage   `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserverConfig) Reset() {
	*x = ObserverConfig{}
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserverConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverConfig) ProtoMessage() {}

func (x *ObserverConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverConfig.ProtoReflect.Descriptor instead.
func (*ObserverConfig) Descriptor() ([]byte, []int) {
	return file_app_observatory_multiobservatory_config_proto_rawDescGZIP(), []int{1}
}

func (x *ObserverConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ObserverConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ObserverConfig) GetSettings() *serial.TypedMessage {
	if x != nil {
		return x.Settings
	}
	return nil
}

type HealthConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SubjectSelector   []string               `protobuf:"bytes,1,rep,name=subject_selector,json=subjectSelector,proto3" json:"subject_selector,omitempty"`
	Method            string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url               string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Interval          int64                  `protobuf:"varint,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout           int64                  `protobuf:"varint,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Concurrency       uint32                 `protobuf:"varint,6,opt,name=concurrency,proto3" json:"concurrency,omitempty"`
	AcceptedStatusMin uint32                 `protobuf:"varint,7,opt,name=accepted_status_min,json=acceptedStatusMin,proto3" json:"accepted_status_min,omitempty"`
	AcceptedStatusMax uint32                 `protobuf:"varint,8,opt,name=accepted_status_max,json=acceptedStatusMax,proto3" json:"accepted_status_max,omitempty"`
	MinBytes          int64                  `protobuf:"varint,9,opt,name=min_bytes,json=minBytes,proto3" json:"min_bytes,omitempty"`
	Policy            *HealthPolicyConfig    `protobuf:"bytes,10,opt,name=policy,proto3" json:"policy,omitempty"`
	IpProvider        *IPProbeProviderConfig `protobuf:"bytes,11,opt,name=ip_provider,json=ipProvider,proto3" json:"ip_provider,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthConfig) Reset() {
	*x = HealthConfig{}
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthConfig) ProtoMessage() {}

func (x *HealthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthConfig.ProtoReflect.Descriptor instead.
func (*HealthConfig) Descriptor() ([]byte, []int) {
	return file_app_observatory_multiobservatory_config_proto_rawDescGZIP(), []int{2}
}

func (x *HealthConfig) GetSubjectSelector() []string {
	if x != nil {
		return x.SubjectSelector
	}
	return nil
}

func (x *HealthConfig) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HealthConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *HealthConfig) GetInterval() int64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *HealthConfig) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *HealthConfig) GetConcurrency() uint32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *HealthConfig) GetAcceptedStatusMin() uint32 {
	if x != nil {
		return x.AcceptedStatusMin
	}
	return 0
}

func (x *HealthConfig) GetAcceptedStatusMax() uint32 {
	if x != nil {
		return x.AcceptedStatusMax
	}
	return 0
}

func (x *HealthConfig) GetMinBytes() int64 {
	if x != nil {
		return x.MinBytes
	}
	return 0
}

func (x *HealthConfig) GetPolicy() *HealthPolicyConfig {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *HealthConfig) GetIpProvider() *IPProbeProviderConfig {
	if x != nil {
		return x.IpProvider
	}
	return nil
}

type IPProbeProviderConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPProbeProviderConfig) Reset() {
	*x = IPProbeProviderConfig{}
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPProbeProviderConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPProbeProviderConfig) ProtoMessage() {}

func (x *IPProbeProviderConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPProbeProviderConfig.ProtoReflect.Descriptor instead.
func (*IPProbeProviderConfig) Descriptor() ([]byte, []int) {
	return file_app_observatory_multiobservatory_config_proto_rawDescGZIP(), []int{3}
}

func (x *IPProbeProviderConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IPProbeProviderConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type HealthPolicyConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Settings      *serial.TypedMessage   `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthPolicyConfig) Reset() {
	*x = HealthPolicyConfig{}
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthPolicyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthPolicyConfig) ProtoMessage() {}

func (x *HealthPolicyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthPolicyConfig.ProtoReflect.Descriptor instead.
func (*HealthPolicyConfig) Descriptor() ([]byte, []int) {
	return file_app_observatory_multiobservatory_config_proto_rawDescGZIP(), []int{4}
}

func (x *HealthPolicyConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HealthPolicyConfig) GetSettings() *serial.TypedMessage {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SlidingWindowPolicyConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WindowSize        *uint32                `protobuf:"varint,1,opt,name=window_size,json=windowSize,proto3,oneof" json:"window_size,omitempty"`
	MinimumSamples    *uint32                `protobuf:"varint,2,opt,name=minimum_samples,json=minimumSamples,proto3,oneof" json:"minimum_samples,omitempty"`
	FailureThreshold  *float64               `protobuf:"fixed64,3,opt,name=failure_threshold,json=failureThreshold,proto3,oneof" json:"failure_threshold,omitempty"`
	RecoveryThreshold *float64               `protobuf:"fixed64,4,opt,name=recovery_threshold,json=recoveryThreshold,proto3,oneof" json:"recovery_threshold,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SlidingWindowPolicyConfig) Reset() {
	*x = SlidingWindowPolicyConfig{}
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlidingWindowPolicyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlidingWindowPolicyConfig) ProtoMessage() {}

func (x *SlidingWindowPolicyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_multiobservatory_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlidingWindowPolicyConfig.ProtoReflect.Descriptor instead.
func (*SlidingWindowPolicyConfig) Descriptor() ([]byte, []int) {
	return file_app_observatory_multiobservatory_config_proto_rawDescGZIP(), []int{5}
}

func (x *SlidingWindowPolicyConfig) GetWindowSize() uint32 {
	if x != nil && x.WindowSize != nil {
		return *x.WindowSize
	}
	return 0
}

func (x *SlidingWindowPolicyConfig) GetMinimumSamples() uint32 {
	if x != nil && x.MinimumSamples != nil {
		return *x.MinimumSamples
	}
	return 0
}

func (x *SlidingWindowPolicyConfig) GetFailureThreshold() float64 {
	if x != nil && x.FailureThreshold != nil {
		return *x.FailureThreshold
	}
	return 0
}

func (x *SlidingWindowPolicyConfig) GetRecoveryThreshold() float64 {
	if x != nil && x.RecoveryThreshold != nil {
		return *x.RecoveryThreshold
	}
	return 0
}

var File_app_observatory_multiobservatory_config_proto protoreflect.FileDescriptor

const file_app_observatory_multiobservatory_config_proto_rawDesc = "" +
	"\n" +
	"-app/observatory/multiobservatory/config.proto\x12*xray.core.app.observatory.multiobservatory\x1a!common/serial/typed_message.proto\"b\n" +
	"\x06Config\x12X\n" +
	"\tobservers\x18\x01 \x03(\v2:.xray.core.app.observatory.multiobservatory.ObserverConfigR\tobservers\"t\n" +
	"\x0eObserverConfig\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12<\n" +
	"\bsettings\x18\x03 \x01(\v2 .xray.common.serial.TypedMessageR\bsettings\"\xf4\x03\n" +
	"\fHealthConfig\x12)\n" +
	"\x10subject_selector\x18\x01 \x03(\tR\x0fsubjectSelector\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\binterval\x18\x04 \x01(\x03R\binterval\x12\x18\n" +
	"\atimeout\x18\x05 \x01(\x03R\atimeout\x12 \n" +
	"\vconcurrency\x18\x06 \x01(\rR\vconcurrency\x12.\n" +
	"\x13accepted_status_min\x18\a \x01(\rR\x11acceptedStatusMin\x12.\n" +
	"\x13accepted_status_max\x18\b \x01(\rR\x11acceptedStatusMax\x12\x1b\n" +
	"\tmin_bytes\x18\t \x01(\x03R\bminBytes\x12V\n" +
	"\x06policy\x18\n" +
	" \x01(\v2>.xray.core.app.observatory.multiobservatory.HealthPolicyConfigR\x06policy\x12b\n" +
	"\vip_provider\x18\v \x01(\v2A.xray.core.app.observatory.multiobservatory.IPProbeProviderConfigR\n" +
	"ipProvider\"=\n" +
	"\x15IPProbeProviderConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"f\n" +
	"\x12HealthPolicyConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12<\n" +
	"\bsettings\x18\x02 \x01(\v2 .xray.common.serial.TypedMessageR\bsettings\"\xa6\x02\n" +
	"\x19SlidingWindowPolicyConfig\x12$\n" +
	"\vwindow_size\x18\x01 \x01(\rH\x00R\n" +
	"windowSize\x88\x01\x01\x12,\n" +
	"\x0fminimum_samples\x18\x02 \x01(\rH\x01R\x0eminimumSamples\x88\x01\x01\x120\n" +
	"\x11failure_threshold\x18\x03 \x01(\x01H\x02R\x10failureThreshold\x88\x01\x01\x122\n" +
	"\x12recovery_threshold\x18\x04 \x01(\x01H\x03R\x11recoveryThreshold\x88\x01\x01B\x0e\n" +
	"\f_window_sizeB\x12\n" +
	"\x10_minimum_samplesB\x14\n" +
	"\x12_failure_thresholdB\x15\n" +
	"\x13_recovery_thresholdB\x91\x01\n" +
	")com.xray.app.observatory.multiobservatoryP\x01Z:github.com/xtls/xray-core/app/observatory/multiobservatory\xaa\x02%Xray.App.Observatory.MultiObservatoryb\x06proto3"

var (
	file_app_observatory_multiobservatory_config_proto_rawDescOnce sync.Once
	file_app_observatory_multiobservatory_config_proto_rawDescData []byte
)

func file_app_observatory_multiobservatory_config_proto_rawDescGZIP() []byte {
	file_app_observatory_multiobservatory_config_proto_rawDescOnce.Do(func() {
		file_app_observatory_multiobservatory_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_observatory_multiobservatory_config_proto_rawDesc), len(file_app_observatory_multiobservatory_config_proto_rawDesc)))
	})
	return file_app_observatory_multiobservatory_config_proto_rawDescData
}

var file_app_observatory_multiobservatory_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_app_observatory_multiobservatory_config_proto_goTypes = []any{
	(*Config)(nil),                    // 0: xray.core.app.observatory.multiobservatory.Config
	(*ObserverConfig)(nil),            // 1: xray.core.app.observatory.multiobservatory.ObserverConfig
	(*HealthConfig)(nil),              // 2: xray.core.app.observatory.multiobservatory.HealthConfig
	(*IPProbeProviderConfig)(nil),     // 3: xray.core.app.observatory.multiobservatory.IPProbeProviderConfig
	(*HealthPolicyConfig)(nil),        // 4: xray.core.app.observatory.multiobservatory.HealthPolicyConfig
	(*SlidingWindowPolicyConfig)(nil), // 5: xray.core.app.observatory.multiobservatory.SlidingWindowPolicyConfig
	(*serial.TypedMessage)(nil),       // 6: xray.common.serial.TypedMessage
}
var file_app_observatory_multiobservatory_config_proto_depIdxs = []int32{
	1, // 0: xray.core.app.observatory.multiobservatory.Config.observers:type_name -> xray.core.app.observatory.multiobservatory.ObserverConfig
	6, // 1: xray.core.app.observatory.multiobservatory.ObserverConfig.settings:type_name -> xray.common.serial.TypedMessage
	4, // 2: xray.core.app.observatory.multiobservatory.HealthConfig.policy:type_name -> xray.core.app.observatory.multiobservatory.HealthPolicyConfig
	3, // 3: xray.core.app.observatory.multiobservatory.HealthConfig.ip_provider:type_name -> xray.core.app.observatory.multiobservatory.IPProbeProviderConfig
	6, // 4: xray.core.app.observatory.multiobservatory.HealthPolicyConfig.settings:type_name -> xray.common.serial.TypedMessage
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_app_observatory_multiobservatory_config_proto_init() }
func file_app_observatory_multiobservatory_config_proto_init() {
	if File_app_observatory_multiobservatory_config_proto != nil {
		return
	}
	file_app_observatory_multiobservatory_config_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_observatory_multiobservatory_config_proto_rawDesc), len(file_app_observatory_multiobservatory_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_observatory_multiobservatory_config_proto_goTypes,
		DependencyIndexes: file_app_observatory_multiobservatory_config_proto_depIdxs,
		MessageInfos:      file_app_observatory_multiobservatory_config_proto_msgTypes,
	}.Build()
	File_app_observatory_multiobservatory_config_proto = out.File
	file_app_observatory_multiobservatory_config_proto_goTypes = nil
	file_app_observatory_multiobservatory_config_proto_depIdxs = nil
}
