// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: app/metrics/config.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config is the settings for metrics.
type Config struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tag of the outbound handler that handles metrics http connections.
	Tag           string               `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Listen        string               `protobuf:"bytes,2,opt,name=listen,proto3" json:"listen,omitempty"`
	Access        *AccessMetricsConfig `protobuf:"bytes,99,opt,name=access,proto3" json:"access,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_app_metrics_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_app_metrics_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_app_metrics_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Config) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *Config) GetAccess() *AccessMetricsConfig {
	if x != nil {
		return x.Access
	}
	return nil
}

// AccessMetricsConfig controls metrics derived from structured access events.
type AccessMetricsConfig struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Sliding window stored as an int64 time.Duration.
	Window    int64  `protobuf:"varint,2,opt,name=window,proto3" json:"window,omitempty"`
	QueueSize uint32 `protobuf:"varint,3,opt,name=queue_size,json=queueSize,proto3" json:"queue_size,omitempty"`
	// Include the normalized source address in request metric labels.
	IncludeFrom bool `protobuf:"varint,4,opt,name=include_from,json=includeFrom,proto3" json:"include_from,omitempty"`
	// Include the normalized effective destination in request metric labels.
	IncludeTo     bool `protobuf:"varint,5,opt,name=include_to,json=includeTo,proto3" json:"include_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessMetricsConfig) Reset() {
	*x = AccessMetricsConfig{}
	mi := &file_app_metrics_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessMetricsConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessMetricsConfig) ProtoMessage() {}

func (x *AccessMetricsConfig) ProtoReflect() protoreflect.Message {
	mi := &file_app_metrics_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessMetricsConfig.ProtoReflect.Descriptor instead.
func (*AccessMetricsConfig) Descriptor() ([]byte, []int) {
	return file_app_metrics_config_proto_rawDescGZIP(), []int{1}
}

func (x *AccessMetricsConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AccessMetricsConfig) GetWindow() int64 {
	if x != nil {
		return x.Window
	}
	return 0
}

func (x *AccessMetricsConfig) GetQueueSize() uint32 {
	if x != nil {
		return x.QueueSize
	}
	return 0
}

func (x *AccessMetricsConfig) GetIncludeFrom() bool {
	if x != nil {
		return x.IncludeFrom
	}
	return false
}

func (x *AccessMetricsConfig) GetIncludeTo() bool {
	if x != nil {
		return x.IncludeTo
	}
	return false
}

var File_app_metrics_config_proto protoreflect.FileDescriptor

const file_app_metrics_config_proto_rawDesc = "" +
	"\n" +
	"\x18app/metrics/config.proto\x12\x10xray.app.metrics\"q\n" +
	"\x06Config\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x16\n" +
	"\x06listen\x18\x02 \x01(\tR\x06listen\x12=\n" +
	"\x06access\x18c \x01(\v2%.xray.app.metrics.AccessMetricsConfigR\x06access\"\xa8\x01\n" +
	"\x13AccessMetricsConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06window\x18\x02 \x01(\x03R\x06window\x12\x1d\n" +
	"\n" +
	"queue_size\x18\x03 \x01(\rR\tqueueSize\x12!\n" +
	"\finclude_from\x18\x04 \x01(\bR\vincludeFrom\x12\x1d\n" +
	"\n" +
	"include_to\x18\x05 \x01(\bR\tincludeToBR\n" +
	"\x14com.xray.app.metricsP\x01Z%github.com/xtls/xray-core/app/metrics\xaa\x02\x10Xray.App.Metricsb\x06proto3"

var (
	file_app_metrics_config_proto_rawDescOnce sync.Once
	file_app_metrics_config_proto_rawDescData []byte
)

func file_app_metrics_config_proto_rawDescGZIP() []byte {
	file_app_metrics_config_proto_rawDescOnce.Do(func() {
		file_app_metrics_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_metrics_config_proto_rawDesc), len(file_app_metrics_config_proto_rawDesc)))
	})
	return file_app_metrics_config_proto_rawDescData
}

var file_app_metrics_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_metrics_config_proto_goTypes = []any{
	(*Config)(nil),              // 0: xray.app.metrics.Config
	(*AccessMetricsConfig)(nil), // 1: xray.app.metrics.AccessMetricsConfig
}
var file_app_metrics_config_proto_depIdxs = []int32{
	1, // 0: xray.app.metrics.Config.access:type_name -> xray.app.metrics.AccessMetricsConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_metrics_config_proto_init() }
func file_app_metrics_config_proto_init() {
	if File_app_metrics_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_metrics_config_proto_rawDesc), len(file_app_metrics_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_metrics_config_proto_goTypes,
		DependencyIndexes: file_app_metrics_config_proto_depIdxs,
		MessageInfos:      file_app_metrics_config_proto_msgTypes,
	}.Build()
	File_app_metrics_config_proto = out.File
	file_app_metrics_config_proto_goTypes = nil
	file_app_metrics_config_proto_depIdxs = nil
}
