// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: app/observatory/status.proto

package observatory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ObserverTag        string                 `protobuf:"bytes,1,opt,name=observer_tag,json=observerTag,proto3" json:"observer_tag,omitempty"`
	OutboundTag        string                 `protobuf:"bytes,2,opt,name=outbound_tag,json=outboundTag,proto3" json:"outbound_tag,omitempty"`
	Method             string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	PolicyState        string                 `protobuf:"bytes,4,opt,name=policy_state,json=policyState,proto3" json:"policy_state,omitempty"`
	EffectiveState     string                 `protobuf:"bytes,5,opt,name=effective_state,json=effectiveState,proto3" json:"effective_state,omitempty"`
	PolicyReason       string                 `protobuf:"bytes,6,opt,name=policy_reason,json=policyReason,proto3" json:"policy_reason,omitempty"`
	Success            bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	CheckedAt          int64                  `protobuf:"varint,8,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"`
	LastSuccess        int64                  `protobuf:"varint,9,opt,name=last_success,json=lastSuccess,proto3" json:"last_success,omitempty"`
	DurationMs         int64                  `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TtfbMs             int64                  `protobuf:"varint,11,opt,name=ttfb_ms,json=ttfbMs,proto3" json:"ttfb_ms,omitempty"`
	HttpStatus         int32                  `protobuf:"varint,12,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	Bytes              int64                  `protobuf:"varint,13,opt,name=bytes,proto3" json:"bytes,omitempty"`
	ErrorStage         string                 `protobuf:"bytes,14,opt,name=error_stage,json=errorStage,proto3" json:"error_stage,omitempty"`
	ErrorReason        string                 `protobuf:"bytes,15,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	WindowSamples      uint64                 `protobuf:"varint,16,opt,name=window_samples,json=windowSamples,proto3" json:"window_samples,omitempty"`
	WindowFailures     uint64                 `protobuf:"varint,17,opt,name=window_failures,json=windowFailures,proto3" json:"window_failures,omitempty"`
	LocationSource     string                 `protobuf:"bytes,18,opt,name=location_source,json=locationSource,proto3" json:"location_source,omitempty"`
	Country            string                 `protobuf:"bytes,19,opt,name=country,proto3" json:"country,omitempty"`
	LocationObservedAt int64                  `protobuf:"varint,20,opt,name=location_observed_at,json=locationObservedAt,proto3" json:"location_observed_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProbeStatus) Reset() {
	*x = ProbeStatus{}
	mi := &file_app_observatory_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeStatus) ProtoMessage() {}

func (x *ProbeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeStatus.ProtoReflect.Descriptor instead.
func (*ProbeStatus) Descriptor() ([]byte, []int) {
	return file_app_observatory_status_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeStatus) GetObserverTag() string {
	if x != nil {
		return x.ObserverTag
	}
	return ""
}

func (x *ProbeStatus) GetOutboundTag() string {
	if x != nil {
		return x.OutboundTag
	}
	return ""
}

func (x *ProbeStatus) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProbeStatus) GetPolicyState() string {
	if x != nil {
		return x.PolicyState
	}
	return ""
}

func (x *ProbeStatus) GetEffectiveState() string {
	if x != nil {
		return x.EffectiveState
	}
	return ""
}

func (x *ProbeStatus) GetPolicyReason() string {
	if x != nil {
		return x.PolicyReason
	}
	return ""
}

func (x *ProbeStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProbeStatus) GetCheckedAt() int64 {
	if x != nil {
		return x.CheckedAt
	}
	return 0
}

func (x *ProbeStatus) GetLastSuccess() int64 {
	if x != nil {
		return x.LastSuccess
	}
	return 0
}

func (x *ProbeStatus) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ProbeStatus) GetTtfbMs() int64 {
	if x != nil {
		return x.TtfbMs
	}
	return 0
}

func (x *ProbeStatus) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *ProbeStatus) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *ProbeStatus) GetErrorStage() string {
	if x != nil {
		return x.ErrorStage
	}
	return ""
}

func (x *ProbeStatus) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *ProbeStatus) GetWindowSamples() uint64 {
	if x != nil {
		return x.WindowSamples
	}
	return 0
}

func (x *ProbeStatus) GetWindowFailures() uint64 {
	if x != nil {
		return x.WindowFailures
	}
	return 0
}

func (x *ProbeStatus) GetLocationSource() string {
	if x != nil {
		return x.LocationSource
	}
	return ""
}

func (x *ProbeStatus) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ProbeStatus) GetLocationObservedAt() int64 {
	if x != nil {
		return x.LocationObservedAt
	}
	return 0
}

type ObserverStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ObserverTag   string                 `protobuf:"bytes,1,opt,name=observer_tag,json=observerTag,proto3" json:"observer_tag,omitempty"`
	Status        []*ProbeStatus         `protobuf:"bytes,2,rep,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObserverStatus) Reset() {
	*x = ObserverStatus{}
	mi := &file_app_observatory_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObserverStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObserverStatus) ProtoMessage() {}

func (x *ObserverStatus) ProtoReflect() protoreflect.Message {
	mi := &file_app_observatory_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObserverStatus.ProtoReflect.Descriptor instead.
func (*ObserverStatus) Descriptor() ([]byte, []int) {
	return file_app_observatory_status_proto_rawDescGZIP(), []int{1}
}

func (x *ObserverStatus) GetObserverTag() string {
	if x != nil {
		return x.ObserverTag
	}
	return ""
}

func (x *ObserverStatus) GetStatus() []*ProbeStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_app_observatory_status_proto protoreflect.FileDescriptor

const file_app_observatory_status_proto_rawDesc = "" +
	"\n" +
	"\x1capp/observatory/status.proto\x12\x19xray.core.app.observatory\"\xb2\x05\n" +
	"\vProbeStatus\x12!\n" +
	"\fobserver_tag\x18\x01 \x01(\tR\vobserverTag\x12!\n" +
	"\foutbound_tag\x18\x02 \x01(\tR\voutboundTag\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12!\n" +
	"\fpolicy_state\x18\x04 \x01(\tR\vpolicyState\x12'\n" +
	"\x0feffective_state\x18\x05 \x01(\tR\x0eeffectiveState\x12#\n" +
	"\rpolicy_reason\x18\x06 \x01(\tR\fpolicyReason\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"checked_at\x18\b \x01(\x03R\tcheckedAt\x12!\n" +
	"\flast_success\x18\t \x01(\x03R\vlastSuccess\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x03R\n" +
	"durationMs\x12\x17\n" +
	"\attfb_ms\x18\v \x01(\x03R\x06ttfbMs\x12\x1f\n" +
	"\vhttp_status\x18\f \x01(\x05R\n" +
	"httpStatus\x12\x14\n" +
	"\x05bytes\x18\r \x01(\x03R\x05bytes\x12\x1f\n" +
	"\verror_stage\x18\x0e \x01(\tR\n" +
	"errorStage\x12!\n" +
	"\ferror_reason\x18\x0f \x01(\tR\verrorReason\x12%\n" +
	"\x0ewindow_samples\x18\x10 \x01(\x04R\rwindowSamples\x12'\n" +
	"\x0fwindow_failures\x18\x11 \x01(\x04R\x0ewindowFailures\x12'\n" +
	"\x0flocation_source\x18\x12 \x01(\tR\x0elocationSource\x12\x18\n" +
	"\acountry\x18\x13 \x01(\tR\acountry\x120\n" +
	"\x14location_observed_at\x18\x14 \x01(\x03R\x12locationObservedAt\"s\n" +
	"\x0eObserverStatus\x12!\n" +
	"\fobserver_tag\x18\x01 \x01(\tR\vobserverTag\x12>\n" +
	"\x06status\x18\x02 \x03(\v2&.xray.core.app.observatory.ProbeStatusR\x06statusB^\n" +
	"\x18com.xray.app.observatoryP\x01Z)github.com/xtls/xray-core/app/observatory\xaa\x02\x14Xray.App.Observatoryb\x06proto3"

var (
	file_app_observatory_status_proto_rawDescOnce sync.Once
	file_app_observatory_status_proto_rawDescData []byte
)

func file_app_observatory_status_proto_rawDescGZIP() []byte {
	file_app_observatory_status_proto_rawDescOnce.Do(func() {
		file_app_observatory_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_app_observatory_status_proto_rawDesc), len(file_app_observatory_status_proto_rawDesc)))
	})
	return file_app_observatory_status_proto_rawDescData
}

var file_app_observatory_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_app_observatory_status_proto_goTypes = []any{
	(*ProbeStatus)(nil),    // 0: xray.core.app.observatory.ProbeStatus
	(*ObserverStatus)(nil), // 1: xray.core.app.observatory.ObserverStatus
}
var file_app_observatory_status_proto_depIdxs = []int32{
	0, // 0: xray.core.app.observatory.ObserverStatus.status:type_name -> xray.core.app.observatory.ProbeStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_app_observatory_status_proto_init() }
func file_app_observatory_status_proto_init() {
	if File_app_observatory_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_app_observatory_status_proto_rawDesc), len(file_app_observatory_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_app_observatory_status_proto_goTypes,
		DependencyIndexes: file_app_observatory_status_proto_depIdxs,
		MessageInfos:      file_app_observatory_status_proto_msgTypes,
	}.Build()
	File_app_observatory_status_proto = out.File
	file_app_observatory_status_proto_goTypes = nil
	file_app_observatory_status_proto_depIdxs = nil
}
